### ISSUE TITLE
Weekly update for reimbursement files

### ISSUE THREAD

**Issue by rodolfo-viana** [datasciencebr/serenata-toolbox#69] opened 2017-05-22 15:27 UTC
I have been updating `reimbursements.xz`, `current-year.xz`, `last-year.xz` and `previous-years.xz` every week. The objective is to use updated data when running analysis locally.

The latest ones are: 

- `2017-05-22-reimbursements.xz`
- `2017-05-22-current-year.xz`
- `2017-05-22-last-year.xz`
- `2017-05-22-previous-years.xz`

Considering they are too big to be attached here (> 10MB), those files are saved in a Google Drive folder. [You can access them here](https://drive.google.com/drive/folders/0BwFZHbCqII9HTlFmeTBSQmNBZm8?usp=sharing).

I will keep updating every Sunday and sharing the Google Drive folder. Feel free to download them and upload to server or save locally whenever you feel like.

**Comment by jtemporal** [comment] 2017-05-23 15:25
I'm closing this one because it only exists for enlightenment purposes.

Thank you very much for this @rodolfo-viana 

# ALERT
If you intend to use any of these datasets to build an notebook on keep in mind that you **will** have to provide a link to it later for reproducibility reasons since at first we **do not** intend to upload these to our S3.

**Closed by jtemporal** 2017-05-23 15:25 UTC
